# Generated by Django 5.1.7 on 2025-04-04 12:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('source_id', models.CharField(max_length=255)),
                ('last_scraped', models.DateField()),
                ('query_no', models.BigIntegerField()),
                ('initial', models.IntegerField()),
                ('max_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='composition_thumbnails/')),
                ('background_video', models.FileField(upload_to='videos/backgrounds/')),
                ('foreground_video', models.FileField(upload_to='videos/foregrounds/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('final_video', models.FileField(blank=True, null=True, upload_to='videos/final/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('brightness', models.IntegerField(default=50)),
                ('saturation', models.IntegerField(default=50)),
                ('opacity', models.IntegerField(default=100)),
                ('transition', models.CharField(choices=[('fade', 'Fade'), ('crossfade', 'Crossfade')], max_length=20)),
                ('background_sources', models.JSONField(default=list)),
                ('foreground_sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='S3Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForegroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='foregrounds/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foregrounds', to='djangoscrap.videocomposition')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='djangoscrap.videocomposition')),
            ],
        ),
    ]
