# Generated by Django 5.1.7 on 2025-04-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoscrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
