# Generated by Django 5.1.7 on 2026-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0002_composition_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="page_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
