# Generated by Django 5.1.7 on 2026-04-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0003_composition_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="transition",
            field=models.CharField(
                choices=[
                    ("none", "No transition"),
                    ("fade", "Fade"),
                    ("crossfade", "Crossfade"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
