# Generated by Django 5.1.7 on 2026-04-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0004_alter_composition_transition"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="playback_speed",
            field=models.FloatField(default=1.0),
        ),
    ]
