# Generated by Django 5.1.7 on 2026-04-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0014_ingestion_batch_and_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonologuePersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "character_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "archetype",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Label for tone (e.g. jock, poet). Used for fallback lines if no corpus is set.",
                        max_length=64,
                    ),
                ),
                (
                    "source_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of reference URLs (social, blogs, news) for future ingestion / RAG.",
                    ),
                ),
                (
                    "style_corpus",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Pasted excerpts or notes that shape voice (your curated training text).",
                    ),
                ),
                (
                    "stream_seed_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional full script: paragraphs separated by blank lines become segments.",
                    ),
                ),
                (
                    "system_prompt_hint",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="For future LLM: system prompt fragment describing the character.",
                    ),
                ),
                ("typing_min_ms", models.PositiveIntegerField(default=28)),
                ("typing_max_ms", models.PositiveIntegerField(default=85)),
                (
                    "pause_between_segments_ms",
                    models.PositiveIntegerField(default=1400),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
