# Generated by Django 5.1.7

from django.db import migrations


def seed_inner_jock(apps, schema_editor):
    MonologuePersona = apps.get_model("djangoscrap", "MonologuePersona")
    from djangoscrap.research_packs import seed_payload

    pack = seed_payload()
    defaults = {
        "title": pack["title"],
        "character_name": pack.get("character_name", ""),
        "archetype": pack.get("archetype", "jock"),
        "source_urls": pack.get("suggested_urls", []),
        "style_corpus": pack.get("style_corpus", ""),
        "stream_seed_text": pack.get("stream_seed_text", ""),
        "system_prompt_hint": pack.get("system_prompt_hint", ""),
        "typing_min_ms": 28,
        "typing_max_ms": 85,
        "pause_between_segments_ms": 1400,
        "is_published": True,
    }
    MonologuePersona.objects.update_or_create(slug=pack["slug"], defaults=defaults)


def unseed_inner_jock(apps, schema_editor):
    MonologuePersona = apps.get_model("djangoscrap", "MonologuePersona")
    MonologuePersona.objects.filter(slug="inner-jock").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0015_monologue_persona"),
    ]

    operations = [
        migrations.RunPython(seed_inner_jock, unseed_inner_jock),
    ]
