# Generated by Django 5.1.7 on 2026-04-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0016_seed_inner_jock_monologue"),
    ]

    operations = [
        migrations.AddField(
            model_name="monologuepersona",
            name="cached_visual_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Image URLs (e.g. og:image) harvested from source_urls for the public page backdrop.",
            ),
        ),
        migrations.AddField(
            model_name="monologuepersona",
            name="visual_cache_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
