# Generated by Django 5.1.7 on 2026-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0017_monologue_visual_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancedThoughtScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "character_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("archetype", models.CharField(blank=True, default="", max_length=80)),
                ("character_brief", models.TextField(blank=True, default="")),
                ("world_context", models.TextField(blank=True, default="")),
                ("tone_hint", models.TextField(blank=True, default="")),
                ("seed_desires", models.JSONField(blank=True, default=list)),
                ("seed_subconscious", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(default=False)),
                ("tick_interval_seconds", models.PositiveIntegerField(default=7)),
                ("last_thought", models.TextField(blank=True, default="")),
                (
                    "last_image_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("last_visual_prompt", models.TextField(blank=True, default="")),
                ("last_desires", models.JSONField(blank=True, default=list)),
                ("last_subconscious", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
