# Generated by Django 5.1.7 on 2026-04-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0018_advanced_thought_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancedthoughtscenario",
            name="continuity_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="advancedthoughtscenario",
            name="current_location",
            field=models.CharField(blank=True, default="bedroom", max_length=255),
        ),
        migrations.AddField(
            model_name="advancedthoughtscenario",
            name="sim_minutes",
            field=models.PositiveIntegerField(default=480),
        ),
    ]
