# Generated by Django 5.1.7 on 2026-04-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0019_advanced_scenario_continuity"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancedthoughtscenario",
            name="relationship_graph",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Key people and relationship dynamics for social continuity.",
            ),
        ),
        migrations.AddField(
            model_name="advancedthoughtscenario",
            name="scene_bible",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stable environment anchors (room objects, recurring visual motifs).",
            ),
        ),
    ]
