# Generated by Django 5.1.7 on 2026-04-15 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0020_advanced_scene_relationships"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("location_type", models.CharField(default="interior", max_length=80)),
                ("x", models.FloatField(default=0.0)),
                ("y", models.FloatField(default=0.0)),
                ("adjacent_slugs", models.JSONField(blank=True, default=list)),
                ("access_rules", models.JSONField(blank=True, default=dict)),
                ("ambient_tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SocialSimWorld",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "timezone",
                    models.CharField(default="America/Los_Angeles", max_length=64),
                ),
                ("sim_day", models.PositiveIntegerField(default=1)),
                ("sim_minute", models.PositiveIntegerField(default=480)),
                ("is_active", models.BooleanField(default=True)),
                ("weather_state", models.JSONField(blank=True, default=dict)),
                ("rhythm_state", models.JSONField(blank=True, default=dict)),
                ("render_policy", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_index", models.PositiveIntegerField(default=1)),
                ("minute_index", models.PositiveIntegerField(default=0)),
                ("event_type", models.CharField(default="ambient", max_length=80)),
                ("actor_slugs", models.JSONField(blank=True, default=list)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("significance", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="djangoscrap.sociallocation",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="djangoscrap.socialsimworld",
                    ),
                ),
            ],
            options={
                "ordering": ["-day_index", "-minute_index", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SocialAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=255)),
                ("identity_packet", models.JSONField(blank=True, default=dict)),
                ("body_state", models.JSONField(blank=True, default=dict)),
                ("mood_state", models.JSONField(blank=True, default=dict)),
                ("goals_state", models.JSONField(blank=True, default=list)),
                ("subconscious_state", models.JSONField(blank=True, default=list)),
                ("working_self", models.TextField(blank=True, default="")),
                ("routine_profile", models.JSONField(blank=True, default=dict)),
                ("tendency_profile", models.JSONField(blank=True, default=dict)),
                ("last_plan", models.TextField(blank=True, default="")),
                ("last_thought", models.TextField(blank=True, default="")),
                ("last_subconscious", models.TextField(blank=True, default="")),
                ("last_rendered_at", models.DateTimeField(blank=True, null=True)),
                ("render_priority", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="present_agents",
                        to="djangoscrap.sociallocation",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="djangoscrap.socialsimworld",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("world", "slug")},
            },
        ),
        migrations.CreateModel(
            name="SocialMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objective_summary", models.TextField(blank=True, default="")),
                ("subjective_summary", models.TextField(blank=True, default="")),
                ("emotional_weight", models.FloatField(default=0.0)),
                ("distortion", models.FloatField(default=0.0)),
                ("unresolved", models.JSONField(blank=True, default=list)),
                ("consolidated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="djangoscrap.socialagent",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memories",
                        to="djangoscrap.socialevent",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="djangoscrap.socialsimworld",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="sociallocation",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="djangoscrap.socialsimworld",
            ),
        ),
        migrations.CreateModel(
            name="SocialRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("unresolved_tensions", models.JSONField(blank=True, default=list)),
                ("shared_history", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_relationships",
                        to="djangoscrap.socialagent",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_relationships",
                        to="djangoscrap.socialagent",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="djangoscrap.socialsimworld",
                    ),
                ),
            ],
            options={
                "unique_together": {("world", "source", "target")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="sociallocation",
            unique_together={("world", "slug")},
        ),
    ]
