# Generated by Django 5.1.7 on 2026-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0021_sociallocation_socialsimworld_socialevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="composition_hashtags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
