# Generated by Django 5.1.7 on 2026-04-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0022_composition_composition_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionitem",
            name="dedupe_note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ingestionitem",
            name="phash",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
