# Generated by Django 5.1.7 on 2026-04-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0023_ingestionitem_dedupe_note_ingestionitem_phash"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionitem",
            name="color_mode",
            field=models.CharField(blank=True, default="unknown", max_length=16),
        ),
        migrations.AddField(
            model_name="ingestionitem",
            name="dominant_color_hex",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="ingestionitem",
            name="height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ingestionitem",
            name="orientation",
            field=models.CharField(blank=True, default="unknown", max_length=16),
        ),
        migrations.AddField(
            model_name="ingestionitem",
            name="width",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
