# Generated by Django 5.1.7 on 2026-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0024_ingestionitem_color_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionbatch",
            name="last_scrape_engine_summary",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ingestionbatch",
            name="last_scrape_report",
            field=models.TextField(blank=True, default=""),
        ),
    ]
