# Generated by Django 5.1.7 on 2026-04-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0031_ingestionbatch_campaign_scheduled_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="overlay_fit",
            field=models.CharField(
                choices=[
                    ("free", "Free (unconstrained)"),
                    ("framed", "Framed (cropped, even borders)"),
                ],
                default="free",
                max_length=16,
            ),
        ),
    ]
