# Generated by Django 5.1.7 on 2026-04-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0032_composition_overlay_fit"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="overlay_frame_margin",
            field=models.FloatField(default=0.12),
        ),
    ]
