# Generated by Django 5.1.7 on 2026-04-20 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0035_composition_allowed_personas"),
    ]

    operations = [
        migrations.CreateModel(
            name="WallProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("rows", models.PositiveIntegerField(default=3)),
                ("cols", models.PositiveIntegerField(default=3)),
                ("strict_live", models.BooleanField(default=True)),
                ("cadence_seconds", models.PositiveIntegerField(default=12)),
                ("start_lead_ms", models.PositiveIntegerField(default=2000)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WallRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stopped", "Stopped"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                        ],
                        default="stopped",
                        max_length=16,
                    ),
                ),
                ("tick", models.PositiveIntegerField(default=0)),
                ("current_tick_id", models.PositiveIntegerField(default=0)),
                ("current_start_at_unix_ms", models.BigIntegerField(default=0)),
                ("current_duration_ms", models.PositiveIntegerField(default=12000)),
                ("active_character_keys", models.JSONField(blank=True, default=list)),
                ("thought_text", models.TextField(blank=True, default="")),
                (
                    "scenario_state",
                    models.CharField(blank=True, default="neutral", max_length=40),
                ),
                (
                    "scene_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("scene_people", models.JSONField(blank=True, default=list)),
                ("pool_composition_ids", models.JSONField(blank=True, default=list)),
                ("pinned_assignments", models.JSONField(blank=True, default=dict)),
                ("previous_assignments", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="djangoscrap.wallprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WallHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_id", models.CharField(max_length=40)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("clock_offset_ms", models.IntegerField(default=0)),
                ("last_applied_tick", models.IntegerField(default=0)),
                ("drift_ms", models.IntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_payload", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeats",
                        to="djangoscrap.wallrun",
                    ),
                ),
            ],
            options={
                "ordering": ["screen_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "screen_id"), name="wall_heartbeat_unique_screen"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WallAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tick_id", models.PositiveIntegerField()),
                ("tile_index", models.PositiveIntegerField()),
                (
                    "layer",
                    models.CharField(blank=True, default="transitional", max_length=24),
                ),
                (
                    "composition_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=120)),
                ("start_at_unix_ms", models.BigIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=12000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "composition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wall_assignments",
                        to="djangoscrap.composition",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="djangoscrap.wallrun",
                    ),
                ),
            ],
            options={
                "ordering": ["tick_id", "tile_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "tick_id", "tile_index"),
                        name="wall_assignment_unique_tick_tile",
                    )
                ],
            },
        ),
    ]
