# Generated by Django 5.1.7 on 2026-04-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0036_wallprofile_wallrun_wallheartbeat_wallassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="nft_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="composition",
            name="nft_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="composition",
            name="nft_external_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="composition",
            name="nft_last_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="composition",
            name="nft_metadata_file",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="composition",
            name="nft_mode",
            field=models.CharField(
                choices=[
                    ("live", "Live (dynamic)"),
                    ("epoch", "Epoch (versioned dynamic)"),
                    ("frozen", "Frozen snapshot"),
                ],
                default="live",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="composition",
            name="nft_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
