# Generated by Django 5.1.7 on 2026-04-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0039_composition_overlay_landscape_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="source_playback_mode",
            field=models.CharField(
                choices=[
                    ("chronological", "Chronological"),
                    ("random", "Randomize across selected sources"),
                ],
                default="random",
                max_length=20,
            ),
        ),
    ]
