# Generated by Django 5.1.7 on 2026-04-25 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0040_alter_composition_source_playback_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompositionNFT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("rendering", "Rendering"),
                            ("ready", "Ready to mint"),
                            ("minted", "Minted"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "chain",
                    models.CharField(
                        choices=[("ethereum", "Ethereum")],
                        default="ethereum",
                        max_length=20,
                    ),
                ),
                ("chain_id", models.PositiveIntegerField(default=1)),
                (
                    "contract_address",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("token_id", models.CharField(blank=True, default="", max_length=128)),
                ("token_uri", models.CharField(blank=True, default="", max_length=500)),
                (
                    "metadata_uri",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("image_uri", models.CharField(blank=True, default="", max_length=500)),
                (
                    "animation_uri",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "local_image_file",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "local_video_file",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "local_metadata_file",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("live_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "owner_wallet",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "minter_wallet",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("tx_hash", models.CharField(blank=True, default="", max_length=128)),
                ("settings_snapshot", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("minted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "composition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nft_versions",
                        to="djangoscrap.composition",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="djangoscrap.compositionnft",
                    ),
                ),
            ],
            options={
                "ordering": ["composition_id", "version_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("composition", "version_number"),
                        name="unique_composition_nft_version",
                    )
                ],
            },
        ),
    ]
