# Generated by Django 5.1.7 on 2026-04-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0043_composition_publish_excluded_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="MintCollectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "collection_title",
                    models.CharField(default="Aggregation Works", max_length=255),
                ),
                (
                    "collection_icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="mint_collection/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mint collection settings",
                "verbose_name_plural": "Mint collection settings",
            },
        ),
    ]
