# Generated by Django 5.1.7 on 2026-04-27 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0044_mintcollectionsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="compositionnft",
            name="local_collector_video_file",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.CreateModel(
            name="CompositionMediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("poster", "Poster still"),
                            ("preview_15s", "15s preview video"),
                            ("collector_45s", "45s collector video"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="nft/generated/"),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("aspect_preset", models.CharField(default="square", max_length=24)),
                (
                    "source_signature",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("rendering", "Rendering"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "composition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="djangoscrap.composition",
                    ),
                ),
            ],
            options={
                "ordering": ["composition_id", "kind"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("composition", "kind"),
                        name="unique_composition_media_asset_kind",
                    )
                ],
            },
        ),
    ]
