# Generated by Django 5.1.7 on 2026-05-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0046_alter_composition_random_link_enabled_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="grid_cell_index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="composition",
            name="grid_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="composition",
            name="overlay_fit",
            field=models.CharField(
                choices=[
                    ("free", "Free (unconstrained)"),
                    ("framed", "Framed (cropped, even borders)"),
                    ("square", "Square (1:1)"),
                    ("portrait", "Portrait (9:16)"),
                ],
                default="free",
                max_length=16,
            ),
        ),
    ]
