# Generated by Django 5.1.7 on 2026-05-03 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0048_backfill_composition_folders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaskAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("face", "Face"),
                            ("hat", "Hat"),
                            ("clothing", "Clothing"),
                            ("accessory", "Accessory"),
                        ],
                        max_length=16,
                    ),
                ),
                ("tier", models.PositiveSmallIntegerField(default=0)),
                ("image", models.ImageField(upload_to="mask_assets/")),
                ("name", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["slot", "tier", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("palette_json", models.JSONField(blank=True, default=dict)),
                ("lore_md", models.TextField(blank=True, default="")),
                (
                    "mint_authority_pubkey",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Mask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "background_source_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("power", models.PositiveSmallIntegerField(default=5)),
                ("speed", models.PositiveSmallIntegerField(default=5)),
                ("wit", models.PositiveSmallIntegerField(default=5)),
                ("charm", models.PositiveSmallIntegerField(default=5)),
                ("fun_level", models.IntegerField(default=0)),
                (
                    "mint_address",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="masks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "accessory",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"slot": "accessory"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="masks_as_accessory",
                        to="djangoscrap.maskasset",
                    ),
                ),
                (
                    "clothing",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"slot": "clothing"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="masks_as_clothing",
                        to="djangoscrap.maskasset",
                    ),
                ),
                (
                    "face",
                    models.ForeignKey(
                        limit_choices_to={"slot": "face"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="masks_as_face",
                        to="djangoscrap.maskasset",
                    ),
                ),
                (
                    "hat",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"slot": "hat"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="masks_as_hat",
                        to="djangoscrap.maskasset",
                    ),
                ),
                (
                    "tribe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="masks",
                        to="djangoscrap.tribe",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MaskBattle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wager_lamports", models.BigIntegerField(default=0)),
                ("wager_mint", models.CharField(blank=True, default="", max_length=64)),
                ("nft_at_stake", models.BooleanField(default=False)),
                (
                    "escrow_account",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("escrowed", "Escrowed"),
                            ("resolved", "Resolved"),
                            ("settled", "Settled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "result_signature",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("seed", models.CharField(blank=True, default="", max_length=64)),
                ("roll_log", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attacker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles_as_attacker",
                        to="djangoscrap.mask",
                    ),
                ),
                (
                    "defender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles_as_defender",
                        to="djangoscrap.mask",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_won",
                        to="djangoscrap.mask",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="maskasset",
            name="tribe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="djangoscrap.tribe",
            ),
        ),
        migrations.AddIndex(
            model_name="maskasset",
            index=models.Index(
                fields=["slot", "tier", "tribe"], name="djangoscrap_slot_2de65c_idx"
            ),
        ),
    ]
