# Generated by Django 5.1.7 on 2026-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "djangoscrap",
            "0049_maskasset_tribe_mask_maskbattle_maskasset_tribe_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="maskbattle",
            name="polymarket_attacker_outcome",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="maskbattle",
            name="polymarket_market_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="maskbattle",
            name="resolution_source",
            field=models.CharField(
                choices=[
                    ("stats", "Stat-based roll"),
                    ("polymarket", "Polymarket market"),
                ],
                default="stats",
                max_length=20,
            ),
        ),
    ]
