# Generated by Django 5.1.7 on 2026-05-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0050_maskbattle_polymarket_attacker_outcome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
