# Generated by Django 5.1.7 on 2026-05-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0051_add_composition_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="compositionmediaasset",
            name="archive",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
