# Generated by Django 5.1.7 on 2026-05-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0054_rename_preview_15s_to_10s"),
    ]

    operations = [
        migrations.AddField(
            model_name="monologuepersona",
            name="adapter_dir",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Filesystem path to the trained LoRA adapter directory.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="monologuepersona",
            name="base_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HuggingFace ID for the MLX base, e.g. mlx-community/Qwen2.5-7B-Instruct-4bit.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="monologuepersona",
            name="corpus_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Imageboard corpus key, e.g. fourchan_fit.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="monologuepersona",
            name="gen_max_tokens",
            field=models.PositiveIntegerField(default=140),
        ),
        migrations.AddField(
            model_name="monologuepersona",
            name="gen_temperature",
            field=models.FloatField(default=0.95),
        ),
        migrations.AddField(
            model_name="monologuepersona",
            name="gen_top_p",
            field=models.FloatField(default=0.95),
        ),
        migrations.AddField(
            model_name="monologuepersona",
            name="image_dir",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Filesystem directory for this character's per-character image pool.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="monologuepersona",
            name="persona_prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="System prompt that sculpts the character's voice for chat + thoughts.",
            ),
        ),
        migrations.AlterField(
            model_name="compositionmediaasset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("poster", "Poster still"),
                    ("preview_10s", "10s preview video"),
                    ("collector_45s", "45s collector video"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="nftmintvoucher",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="new chat", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="djangoscrap.monologuepersona",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("anon", "anon")], max_length=8
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="djangoscrap.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteThought",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_thoughts",
                        to="djangoscrap.monologuepersona",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
