# Generated by Django 5.1.7 on 2026-05-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0055_monologuepersona_adapter_dir_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
