# Generated by Django 5.1.7 on 2026-05-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoscrap", "0060_composition_source_image_transforms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="source_image_transforms",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
