from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import list_buckets, bucket_contents, upload_file,create_video,user_logout,delete_compositions
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.urls import reverse_lazy
from django.urls import re_path
from django.urls import include
from .views import S3BucketAjaxView,create_bucket
from django.views.generic import RedirectView

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path('', views.fit_chat_page, name='home'),
    # Explicit aliases that cannot collide with browser autocomplete of the
    # admin's /s3/<bucket>/ source library. Bookmark these.
    path('chat/', views.fit_chat_page, name='fit_chat'),
    path('wall/', views.fit_stream_page, name='wall_shortcut'),
    path('fit/', views.fit_chat_page, name='fit_chat_alt'),
    path('api/fit/feedback/', views.fit_thought_feedback, name='fit_thought_feedback'),
    path('api/fit/stream-next/', views.fit_wall_stream_next, name='fit_wall_stream_next'),
    path('service/', views.service, name='service'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('register/', views.register, name='register'),
    path('mint/', views.mint_site, name='mint_site'),
    path('mint/random/', views.mint_random_page, name='mint_random'),
    path('mint/<slug:page_slug>/', views.mint_composition_page, name='mint_composition'),

    # Custom Admin Panel
    path('my-admin/', views.admin_login, name='admin-login'),
    path('admin-dashboard/', views.admin_dashboard, name='admin-dashboard'),
    path('mint-settings/', views.mint_collection_settings, name='mint-collection-settings'),
    path('composition-add/', views.add_composition, name='composition-add'),
    path('composition-edit/<int:composition_id>/', views.add_composition, name='composition-edit'),
    path('composition-view/', views.composition_view, name='composition-view'),
    path('associations-studio/', views.associations_studio, name='associations_studio'),
    path('associations-compare/', views.associations_compare, name='associations_compare'),
    path('aggregation-library/', views.aggregation_library, name='aggregation_library'),
    path('composition/<int:composition_id>/set-ready/', views.set_composition_ready, name='set_composition_ready'),
    path('composition/<int:composition_id>/duplicate/', views.composition_duplicate, name='composition_duplicate'),
    path('composition/<int:composition_id>/generate-grid/', views.composition_generate_grid, name='composition_generate_grid'),
    path('composition/<int:composition_id>/reset-folder/', views.composition_folder_reset, name='composition_folder_reset'),
    path('grid/<str:grid_id>/', views.composition_grid_view, name='composition_grid_view'),
    path('folder/<str:grid_id>/', views.composition_folder_view, name='composition_folder_view'),
    path('composition-live/<int:composition_id>/', views.composition_live_by_id, name='composition_live_by_id'),
    path('compositions/seed-character/', views.seed_character_compositions, name='seed_character_compositions'),
    # Legacy plural URL — bookmarks and muscle memory used /compositions/<id>/
    path(
        "compositions/<int:composition_id>/",
        RedirectView.as_view(pattern_name="composition_detail", permanent=False),
        name="composition_detail_legacy",
    ),
    path('series-library/', views.series_library, name='series-library'),
    path('series-library/<int:series_id>/', views.series_detail, name='series-detail'),
    path('composition-preview/<int:composition_id>/', views.composition_preview_image, name='composition-preview'),
    path('new-source/', views.new_source, name='new-source'),
    path('source-library/', views.source_library, name='source-library'),
    path('source-library/refresh/', views.refresh_source_library, name='refresh_source_library'),
    path('source-library/dedupe/', views.dedupe_source_folders, name='dedupe_source_folders'),
    path('ingestion/', views.ingestion_batches, name='ingestion_batches'),
    path('ingestion/<int:batch_id>/', views.ingestion_batch_detail, name='ingestion_batch_detail'),
    path('ingestion/<int:batch_id>/seed-preview/', views.ingestion_batch_seed_preview, name='ingestion_batch_seed_preview'),
    path('ingestion/<int:batch_id>/status.json', views.ingestion_batch_status, name='ingestion_batch_status'),
    path('ingestion/<int:batch_id>/bulk-ajax/', views.ingestion_batch_bulk_ajax, name='ingestion_batch_bulk_ajax'),
    path('ingestion/campaigns/tick/', views.ingestion_campaign_tick, name='ingestion_campaign_tick'),
    path('ingestion/item/<int:item_id>/decision/', views.ingestion_item_decision, name='ingestion_item_decision'),
    path('audio-sources/new/', views.new_audio_source, name='new-audio-source'),
    path('audio-sources/', views.audio_source_library, name='audio-source-library'),
    path('audio-sources/map/', views.audio_source_map_json, name='audio_source_map_json'),
    path('audio-sources/noise-studio/delete-track/', views.delete_noise_studio_track, name='delete_noise_studio_track'),
    path('audio-sources/create/', views.create_audio_source, name='create_audio_source'),
    path('audio-sources/noise-studio/save/', views.noise_studio_save, name='noise_studio_save'),
    path('audio-sources/noise-studio/', views.noise_studio, name='noise-studio'),
    path('audio-sources/<str:source_name>/', views.audio_source_contents, name='audio_source_contents'),
    path('audio-sources/<str:source_name>/rename/', views.rename_audio_source, name='rename_audio_source'),
    path('audio-sources/<str:source_name>/upload/', views.upload_audio_to_source, name='upload_audio_to_source'),
    path('audio-sources/<str:source_name>/delete-files/', views.delete_audio_source_files, name='delete_audio_source_files'),
    path('audio-sources/<str:source_name>/download-files/', views.download_audio_source_files, name='download_audio_source_files'),
    path('audio-sources/delete/', views.delete_audio_sources, name='delete_audio_sources'),
    path('dashboard/', views.admin_dashboard, name='dashboard'),
    path('delete_compositions/', views.delete_compositions, name='delete_compositions'),
    path('assign-compositions-series/', views.assign_compositions_series, name='assign_compositions_series'),
    path('composition/<int:composition_id>/', views.composition_detail, name='composition_detail'),
    path('composition/<int:composition_id>/nft/image.jpg', views.composition_nft_image, name='composition_nft_image'),
    path('composition/<int:composition_id>/nft/video.mp4', views.composition_nft_video, name='composition_nft_video'),
    path('composition/<int:composition_id>/nft/metadata.json', views.composition_nft_metadata, name='composition_nft_metadata'),
    path('composition/<int:composition_id>/nft/status.json', views.composition_nft_status, name='composition_nft_status'),
    path('composition/<int:composition_id>/nft/prepare/', views.composition_prepare_nft_version, name='composition_prepare_nft_version'),
    path('composition/<int:composition_id>/nft/record-mint/', views.composition_record_nft_mint, name='composition_record_nft_mint'),
    path('nft/version/<int:nft_id>/image.jpg', views.composition_nft_version_image, name='composition_nft_version_image'),
    path('nft/version/<int:nft_id>/video.mp4', views.composition_nft_version_video, name='composition_nft_version_video'),
    path('nft/version/<int:nft_id>/collector-video.mp4', views.composition_nft_version_collector_video, name='composition_nft_version_collector_video'),
    path('nft/version/<int:nft_id>/metadata.json', views.composition_nft_version_metadata, name='composition_nft_version_metadata'),
    path('composition/<int:composition_id>/nft/generate/', views.composition_generate_nft, name='composition_generate_nft'),
    path('composition/<int:composition_id>/nft/media/generate/', views.composition_generate_nft_media, name='composition_generate_nft_media'),
    path('composition/<int:composition_id>/generate-media/', views.composition_generate_media_single, name='composition_generate_media_single'),
    path('composition/<int:composition_id>/media-status/', views.composition_media_status, name='composition_media_status'),
    path('composition/<int:composition_id>/nft/voucher/', views.composition_voucher_sign, name='composition_voucher_sign'),
    path('composition/<int:composition_id>/nft/voucher/redeem/', views.composition_voucher_record_redeem, name='composition_voucher_record_redeem'),
    path('composition/<int:composition_id>/nft/media/<str:kind>/delete/', views.composition_nft_media_delete, name='composition_nft_media_delete'),
    path('composition/<int:composition_id>/nft/media/<str:kind>/archive/delete/', views.composition_nft_media_archive_delete, name='composition_nft_media_archive_delete'),
    path('composition/<int:composition_id>/nft/media/<str:kind>/archive/reinstate/', views.composition_nft_media_archive_reinstate, name='composition_nft_media_archive_reinstate'),
    path('nft/media/generate-all/', views.generate_all_nft_media, name='generate_all_nft_media'),
    path('nft/media/generate-selected/', views.generate_selected_nft_media, name='generate_selected_nft_media'),
    path('nft/launchpad/', views.nft_launchpad, name='nft-launchpad'),
    path('composition/<int:composition_id>/delete/', views.composition_delete, name='composition_delete'),
    path('composition/<int:composition_id>/latest-render/', views.composition_latest_render, name='composition_latest_render'),
    path('composition/<int:composition_id>/render-export/', views.render_composition_export, name='render_composition_export'),
    path('composition/<int:composition_id>/publish/diff/', views.composition_publish_diff, name='composition_publish_diff'),
    path('composition/<int:composition_id>/publish/release/', views.composition_publish_release, name='composition_publish_release'),
    path('composition/<int:composition_id>/publish/rollback/<int:release_id>/', views.composition_release_rollback, name='composition_release_rollback'),
    path('composition/<int:composition_id>/files/inventory/', views.composition_file_inventory, name='composition_file_inventory'),
    path('composition/<int:composition_id>/files/action/', views.composition_file_action, name='composition_file_action'),
    path('source-library/delete/', views.delete_buckets, name='delete_buckets'),
    path('source-library/<str:bucket_name>/trim-borders/', views.trim_source_borders, name='trim_source_borders'),
    path('source-library/download/', views.download_buckets, name='download_buckets'),
    path('delete-bucket/', views.delete_bucket, name='delete_bucket'),
    path('delete-bucket-files/<str:bucket_name>/<path:file_name>/', views.delete_file_from_bucket, name='delete_file_from_bucket'),
    path('generate-video/<int:comp_id>/', views.generate_video, name='generate_video'),

    # Login & Logout 
    path('login/', LoginView.as_view(template_name='login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', views.user_logout, name='logout'),  # Use your custom logout view

    # S3 Bucket URLs
    path('s3/', list_buckets, name='list_buckets'),
    path('s3/<str:bucket_name>/', bucket_contents, name='bucket_contents'),
    path('s3/<str:bucket_name>/upload/', upload_file, name='upload_file'),
    path('s3/<str:bucket_name>/rename/', views.rename_source, name='rename_source'),
    path('s3/<str:bucket_name>/delete-files/', views.delete_source_files, name='delete_source_files'),
    path('s3/<str:bucket_name>/download-files/', views.download_source_files, name='download_source_files'),
    path('s3/<str:bucket_name>/delete-duplicates/', views.delete_duplicate_source_images, name='delete_duplicate_source_images'),
    path('s3/<str:bucket_name>/remove-stray-files/', views.remove_stray_source_files, name='remove_stray_source_files'),
    path("create-bucket/", create_bucket, name="create_bucket"),


    path("create-video/", create_video, name="create-video"),
    path("training-set-media/<path:file_name>", views.training_set_media_file, name="training_set_media_file"),
    path("source-media/<str:source_name>/<path:file_name>", views.source_media_file, name="source_media_file"),
    path("association-chain-media/<str:chain_name>/<path:file_name>", views.association_chain_media_file, name="association_chain_media_file"),
    path("source-thumbnail/<str:source_name>/<path:file_name>", views.source_thumbnail_image, name="source_thumbnail_image"),
    path("source-preview-assets/", views.source_preview_assets, name="source_preview_assets"),
    path("api/associations/next/", views.associations_next_asset, name="associations_next_asset"),
    path("api/associations/candidates/", views.associations_candidates, name="associations_candidates"),
    path("api/associations/select-winner/", views.associations_select_winner, name="associations_select_winner"),
    path("api/associations/bootstrap-training/", views.associations_bootstrap_training, name="associations_bootstrap_training"),
    path("api/associations/feedback-stats/", views.associations_feedback_stats, name="associations_feedback_stats"),
    path("api/associations/image-proxy/", views.associations_image_proxy, name="associations_image_proxy"),
    path("api/associations/feedback/", views.associations_feedback, name="associations_feedback"),
    path("api/associations/store/", views.associations_store_asset, name="associations_store_asset"),
    path("api/compositions/by-hashtag/<slug:hashtag>/", views.compositions_by_hashtag, name="compositions_by_hashtag"),
    path("audio-source-media/<str:source_name>/<path:file_name>", views.audio_source_media_file, name="audio_source_media_file"),
    re_path(r"^media/renders/render_(?P<composition_id>\d+)_.*\.mp4$", views.legacy_render_redirect, name="legacy_render_redirect"),
    path("thoughts/<slug:slug>/", views.monologue_public_page, name="monologue_public"),
    path("api/monologue/<slug:slug>/segment/", views.monologue_next_segment, name="monologue_segment"),
    path("api/monologue/<slug:slug>/background-images/", views.monologue_background_images, name="monologue_background_images"),
    path("character-thoughts/", views.monologue_list, name="monologue_list"),
    path("character-thoughts/lab/", views.thoughtscape_lab, name="thoughtscape_lab"),
    path("character-thoughts/wall/", views.wall_operator, name="wall_operator"),
    path("character-thoughts/fit/", views.fit_operator, name="fit_operator"),
    path("api/fit/thought/", views.fit_operator_thought, name="fit_operator_thought"),

    # Unified per-character pages + slug-scoped API
    path("characters/", views.character_hub, name="character_hub"),
    path("scrape-monitor/", views.scrape_monitor_page, name="scrape_monitor_page"),
    path("avatar/", views.avatar_page, name="avatar_page"),
    path("studio/3d/", views.studio_3d_page, name="studio_3d_page"),
    path("play/wojak/", views.wojak_play_page, name="wojak_play_page"),
    path("play/template/", views.template_play_page, name="template_play_page"),
    path("api/studio3d/library/", views.studio_3d_library, name="studio_3d_library"),
    path("api/studio3d/file/", views.studio_3d_file, name="studio_3d_file"),
    path("greenscreen/", views.greenscreen_page, name="greenscreen_page"),
    path("api/greenscreen/bg-pool/<str:key>/", views.greenscreen_bg_pool, name="greenscreen_bg_pool"),
    path("api/greenscreen/bg-image/<str:key>/", views.greenscreen_bg_image, name="greenscreen_bg_image"),
    path("api/greenscreen/settings/<str:clip_key>/", views.greenscreen_settings_get, name="greenscreen_settings_get"),
    path("api/greenscreen/settings/<str:clip_key>/save/", views.greenscreen_settings_save, name="greenscreen_settings_save"),
    path("api/scrape-monitor/", views.scrape_monitor_data, name="scrape_monitor_data"),
    path("api/scrape-monitor/samples/", views.scrape_monitor_samples, name="scrape_monitor_samples"),
    path("image-scrape-monitor/", views.image_scrape_monitor_page, name="image_scrape_monitor_page"),
    path("api/image-scrape-monitor/", views.image_scrape_monitor_data, name="image_scrape_monitor_data"),
    path("api/image-scrape-monitor/samples/", views.image_scrape_monitor_samples, name="image_scrape_monitor_samples"),
    path("api/image-monitor/thumb/", views.image_scrape_monitor_thumb, name="image_scrape_monitor_thumb"),
    path("api/image-scrape-monitor/recompute/", views.image_scrape_monitor_recompute, name="image_scrape_monitor_recompute"),
    path("api/image-scrape-monitor/recompute-status/", views.image_scrape_monitor_recompute_status, name="image_scrape_monitor_recompute_status"),
    path("api/image-monitor/cluster/", views.image_curation_cluster, name="image_curation_cluster"),
    path("api/image-monitor/decide/", views.image_curation_decide, name="image_curation_decide"),
    path("api/image-monitor/decide-cluster/", views.image_curation_decide_cluster, name="image_curation_decide_cluster"),
    path("api/image-monitor/decision-counts/", views.image_curation_counts, name="image_curation_counts"),
    path("api/image-monitor/search/", views.image_search, name="image_search"),
    path("api/image-monitor/search-index-stats/", views.search_index_stats, name="search_index_stats"),
    path("api/image-monitor/save-named-cluster/", views.save_named_cluster, name="save_named_cluster"),
    path("api/image-monitor/named-clusters/", views.named_clusters_index, name="named_clusters_index"),
    path("api/image-monitor/named-cluster/", views.named_cluster_detail, name="named_cluster_detail"),
    path("api/image-monitor/search-by-image/", views.image_search_by_image, name="image_search_by_image"),
    path("api/image-monitor/search-refine/", views.image_search_refine, name="image_search_refine"),
    path("api/image-monitor/aesthetic-clusters/", views.aesthetic_clusters_index, name="aesthetic_clusters_index"),
    path("api/image-monitor/aesthetic-cluster/", views.aesthetic_cluster_members, name="aesthetic_cluster_members"),
    path("api/image-monitor/ranker/refit/", views.ranker_refit, name="ranker_refit"),
    path("api/image-monitor/ranker/state/", views.ranker_state, name="ranker_state"),
    path("api/image-monitor/ranker/scores/", views.ranker_scores, name="ranker_scores"),
    path("characters/new/", views.character_create, name="character_create"),
    path("characters/<slug:slug>/", views.character_page, name="character_page"),
    path("characters/<slug:slug>/settings/", views.character_settings_save, name="character_settings_save"),
    path("characters/<slug:slug>/delete/", views.character_delete, name="character_delete"),
    path("characters/<slug:slug>/image/<path:relpath>", views.character_image_serve, name="character_image_serve"),

    # Per-character API
    path("api/characters/<slug:slug>/chat/sessions/", views.api_chat_sessions, name="api_chat_sessions"),
    path("api/characters/<slug:slug>/chat/sessions/create/", views.api_chat_session_create, name="api_chat_session_create"),
    path("api/characters/<slug:slug>/chat/sessions/<int:session_id>/", views.api_chat_messages, name="api_chat_messages"),
    path("api/characters/<slug:slug>/chat/sessions/<int:session_id>/send/", views.api_chat_send, name="api_chat_send"),
    path("api/characters/<slug:slug>/chat/sessions/<int:session_id>/delete/", views.api_chat_session_delete, name="api_chat_session_delete"),
    path("api/characters/<slug:slug>/favorites/", views.api_favorites, name="api_favorites"),
    path("api/characters/<slug:slug>/favorites/add/", views.api_favorite_add, name="api_favorite_add"),
    path("api/characters/<slug:slug>/favorites/<int:fav_id>/delete/", views.api_favorite_delete, name="api_favorite_delete"),
    path("api/characters/<slug:slug>/images/", views.api_images, name="api_images"),
    path("api/characters/<slug:slug>/images/upload/", views.api_image_upload, name="api_image_upload"),
    path("api/characters/<slug:slug>/training/", views.api_training, name="api_training"),
    path("wall/player/<str:screen_id>/", views.wall_player, name="wall_player"),
    path("api/thoughtscape/lab/simulate/", views.thoughtscape_lab_simulate, name="thoughtscape_lab_simulate"),
    path("api/wall/state", views.wall_state, name="wall_state"),
    path("api/wall/control", views.wall_control, name="wall_control"),
    path("api/wall/heartbeat", views.wall_heartbeat, name="wall_heartbeat"),
    path("character-thoughts/advanced/", views.advanced_thoughts, name="advanced_thoughts"),
    path("character-thoughts/advanced/new/", views.advanced_thoughts_edit, name="advanced_thoughts_add"),
    path("character-thoughts/advanced/<int:scenario_id>/edit/", views.advanced_thoughts_edit, name="advanced_thoughts_edit"),
    path("character-thoughts/advanced/<int:scenario_id>/delete/", views.advanced_thoughts_delete, name="advanced_thoughts_delete"),
    path("character-thoughts/new/", views.monologue_edit, name="monologue_add"),
    path("character-thoughts/<int:persona_id>/edit/", views.monologue_edit, name="monologue_edit"),
    path("character-thoughts/<int:persona_id>/ai-research/", views.monologue_ai_research, name="monologue_ai_research"),
    path("character-thoughts/<int:persona_id>/delete/", views.monologue_delete, name="monologue_delete"),
    path("advanced-thoughts/<slug:slug>/", views.advanced_thoughts_public, name="advanced_thoughts_public"),
    path("api/advanced-thoughts/<slug:slug>/tick/", views.advanced_thoughts_tick, name="advanced_thoughts_tick"),
    path("sim-artwork/", include("djangoscrap.sim_artwork.urls")),
    path("collect/<slug:page_slug>/", views.composition_collect_page, name="composition_collect_page"),
    # Masks
    path("admin/masks/", views.mask_admin_view, name="mask-view"),
    path("admin/masks/studio/", views.mask_studio_view, name="mask-studio"),
    path("admin/masks/asset/<int:asset_id>/delete/", views.mask_asset_delete_view, name="mask-asset-delete"),
    path("admin/masks/tribe/new/", views.tribe_create_view, name="tribe-create"),
    path("admin/masks/new/", views.mask_edit_view, name="mask-add"),
    path("admin/masks/<int:mask_id>/edit/", views.mask_edit_view, name="mask-edit"),
    path("arena/", views.mask_arena_view, name="mask-arena"),
    path("api/mask/<slug:slug>/", views.mask_detail_api, name="mask-detail-api"),
    path("api/battle/intent/", views.battle_intent_view, name="battle-intent"),
    path("api/battle/<int:battle_id>/resolve/", views.battle_resolve_view, name="battle-resolve"),
    path("api/wallet/link/", views.wallet_link_view, name="wallet-link"),
    path("api/health/", views.health_view, name="api-health"),
    path("api/page_beacon/", views.page_beacon_view, name="api-page-beacon"),
    path("admin/health/", views.health_dashboard, name="admin-health"),
    path('<slug:page_slug>/', views.composition_public_page, name='composition_public_page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    
