name: Test AWS Connection

on:
  workflow_dispatch:  # lets you run it manually

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change if you're using another region

      - name: Test AWS auth
        run: aws sts get-caller-identity
